export const GET_FILES_SUCCESS = 'GET FILES SUCCESS';
export const GET_FILES_FAIL = 'GET FILES FAIL';
export const GET_FILES_REQUEST = 'GET FILES REQUEST';

export const SET_USER_DATA = 'SET USER DATA';
export const REMOVE_USER_DATA = 'REMOVED USER DATA';

export const USER_STATUS = 'USER STATUS';
export const FILES_STATUS = 'FILES STATUS';

export const DELETE_FILE_REQUEST = 'DELETE FILE REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE FILE SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE FILE ERROR';

export const DELETE_TAG_REQUEST = 'DELETE TAG REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE TAG SUCCESS';
export const DELETE_TAG_ERROR = 'DELETE TAG ERROR';

export const SAVE_TAG_REQUEST = 'SAVE TAG REQUEST';
export const SAVE_TAG_SUCCESS = 'SAVE TAG SUCCESS';
export const SAVE_TAG_ERROR = 'SAVE TAG ERROR';

export const ADD_DURATION = 'ADD DURATION';
export const ADD_SIZE = 'ADD SIZE';

export const SET_ERROR = 'SET ERROR';
export const HIDE_ERROR = 'HIDE ERROR';
