export const GET_FILES_SUCCESS = 'GET FILES SUCCESS';
export const GET_FILES_FAIL = 'GET FILES FAIL';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SET_USER_DATA = 'SET USER DATA';
export const REMOVE_USER_DATA = 'REMOVED USER DATA';
export const USER_LOGGED_OUT = 'USER LOGGED OUT';


